name: Merge Batch Data

on:
  workflow_dispatch:  # Chạy thủ công khi nhấn nút "Run workflow"

jobs:
  merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Cấp quyền ghi vào repo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download all batch data
        uses: actions/download-artifact@v4
        with:
          path: data/

      - name: List downloaded files
        run: ls -lah data/

      - name: Run merge_data.py
        run: python merge_data.py || echo "Merge script failed, check logs."

      - name: Upload Merged File as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: merged-vgsales-data
          path: data/vgsales_final.csv
          if-no-files-found: error

      - name: Commit & Push Merged Data
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git pull --rebase origin master || echo "⚠️ Pull failed, continuing..."
          
          git add data/vgsales_final.csv
          if git diff --cached --quiet; then
            echo "⚠️ No changes detected, skipping commit."
          else
            git commit -m "Updated merged vgsales data"
            git push origin master
          fi

      - name: Clean Up Batch Files
        run: rm -rf data/vgsales_updated_*.csv || echo "⚠️ No batch files to delete."
