name: Run Full Pipeline

on:
  workflow_dispatch:  # Chạy thủ công trên GitHub Actions

jobs:
  prepare:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      batch_ids: ${{ steps.set-batch.outputs.batch_ids }}  # 🔥 Xuất batch_ids để truyền sang scrape

    steps:
    
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Generate batch list
        id: set-batch
        run: |
          BATCH_IDS=$(seq 0 19 | jq -R -s 'split("\n")[:-1]' | jq -c)
          echo "Generated batch_ids: $BATCH_IDS"
          
          # 🔥 Đúng cú pháp cho GitHub Actions
          echo "batch_ids=$BATCH_IDS" >> "$GITHUB_OUTPUT"
        shell: bash

      # 🏆 Cache toàn bộ môi trường Python để dùng lại ở các job sau
      - name: Cache Python environment
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip  # Lưu cache thư viện pip
          key: python-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            python-${{ runner.os }}-

      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"


      - name: Install dependencies (if not cached)
        run: pip install -r requirements.txt
        
  crawl-list:
    needs: prepare  # 🛑 Đảm bảo chạy sau khi `prepare` hoàn thành
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Cấp quyền ghi vào repo
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Sử dụng token để có quyền push

      # ✅ Dùng lại cache Python từ `prepare`
      - name: Restore Python environment
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: python-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            python-${{ runner.os }}-
            
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies (if not cached)
        run: pip install -r requirements.txt

          
      - name: Run VGChartz Full Scraper
        run: python -u source/vgchartzfull.py || echo "Script failed, check logs."

      - name: Commit & Push Scraped Data
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add .
          if git diff --cached --quiet; then
            echo "⚠️ No changes detected, skipping commit."
          else
            git commit -m "Updated VGChartz full scraped data"
            git push origin master || (echo "⚠️ Push failed, retrying..." && sleep 10 && git push origin master)
          fi

      # 📌 Lưu file vgsales.csv vào artifact để dùng trong job scrape
      - name: Upload vgsales.csv as artifact
        uses: actions/upload-artifact@v4
        with:
          name: vgsales-data
          path: data/vgsales.csv
          if-no-files-found: error  # Báo lỗi nếu file không tồn tại

  scrape:
    needs: [prepare, crawl-list]  # 🛑 Đảm bảo chạy sau khi `prepare` hoàn thành
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Cấp quyền ghi vào repo
    timeout-minutes: 330  # ⏳ Hủy job nếu chạy quá 5 giờ 30 phút

    strategy:
      matrix:
        batch_id: ${{ fromJson(needs.prepare.outputs.batch_ids) }}
      fail-fast: false  # 🔥 Không hủy các batch khác nếu một batch bị lỗi

    steps:
      - name: Check Memory Usage
        run: free -h

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Sử dụng token để có quyền push

      # ✅ Dùng lại cache Python từ `prepare`
      - name: Restore Python environment
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: python-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            python-${{ runner.os }}-
            
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies (if not cached)
        run: pip install -r requirements.txt

      - name: Ensure vgsales.csv exists, otherwise pull latest data
        run: |
          FILE_PATH="data/vgsales.csv"

          if [ ! -f "$FILE_PATH" ]; then
            echo "⚠️ $FILE_PATH not found! Pulling latest data..."
            
            # 🛠️ Thử pull từ GitHub repo
            git pull origin master || echo "⚠️ Pull failed, checking artifact..."

            # 🔄 Nếu vẫn không có, thử tải từ artifact
            if [ ! -f "$FILE_PATH" ]; then
              echo "⚠️ File still missing! Trying to download from artifact..."
              gh run download -n vgsales-data --dir data/ || echo "⚠️ Artifact not found, skipping..."
            fi
          else
            echo "✅ $FILE_PATH already exists, skipping pull."
          fi

      
      - name: Run genre.py for Batch ${{ matrix.batch_id }}
        run: python -u source/genre.py ${{ matrix.batch_id }} 3302 || echo "Script failed, check logs."
      
      
      - name: Upload CSV Progress
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: vgsales-progress-batch-${{ matrix.batch_id }}
          path: data/vgsales_updated_${{ matrix.batch_id }}.csv
          if-no-files-found: warn
          overwrite: true  # 🔥 Cho phép ghi đè nếu file đã tồn tại

  extract-csv:
    needs: [prepare, scrape]  # Chạy sau khi tất cả batch hoàn thành
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # ✅ Dùng lại cache Python từ `prepare`
      - name: Restore Python environment
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: python-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            python-${{ runner.os }}-
            
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies (if not cached)
        run: pip install -r requirements.txt

      - name: Download all Batch Results
        uses: actions/download-artifact@v4
        with:
          path: batch-results/

      - name: List downloaded files
        run: ls -lah batch-results/

      - name: Move all CSV files to data/
        run: |
          mkdir -p data/  # Đảm bảo thư mục `data/` tồn tại
          find batch-results/ -type f -name "vgsales_updated_*.csv" -exec mv {} data/ \;
          ls -lah data/  # Kiểm tra sau khi di chuyển

      - name: Commit & Push all Batch Updates
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          # 🛠️ Cập nhật repo với phiên bản mới nhất
          git pull --rebase origin master || echo "⚠️ Pull failed, continuing..."

          # ✅ Chỉ add file .csv trong `data/`, bỏ qua thư mục khác
          git add data/*.csv || echo "⚠️ No CSV files to add."

          # 🛑 Kiểm tra xem có thay đổi nào chưa commit không
          if git diff --cached --quiet; then
            echo "⚠️ No changes detected, skipping commit."
            exit 0
          fi

          # 🚀 Commit tất cả file CSV cùng một lúc
          git commit -m "🔥 Updated all batch CSV files"

          # 🔄 Thử push, nếu thất bại thì thử lại nhiều lần với delay random
          while true; do
            if git push origin master; then
              echo "✅ Push successful!"
              exit 0
            else
              SLEEP_TIME=$(shuf -i 1-10 -n 1)  # Random số giây từ 1-10
              echo "⚠️ Push failed, retrying in $SLEEP_TIME seconds..."
              sleep $SLEEP_TIME
              git pull --rebase origin master || echo "⚠️ Pull failed, continuing..."
            fi
          done

  final-commit:
    needs: [prepare, extract-csv]  # Chạy sau khi tất cả batch hoàn thành
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      # ✅ Dùng lại cache Python từ `prepare`
      - name: Restore Python environment
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: python-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            python-${{ runner.os }}-
            
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies (if not cached)
        run: pip install -r requirements.txt

      - name: Ensure latest update, otherwise pull latest data
        run: |
          git pull origin master || echo "⚠️ Pull failed, checking artifact..."
        
      - name: Run merge_data.py
        run: python source/merge_data.py || echo "Merge script failed, check logs."


      - name: Commit & Push Merged Data
        run: |
            git config --global user.name "github-actions"
            git config --global user.email "actions@github.com"
            git pull --rebase origin master || echo "⚠️ Pull failed, continuing..."
            
            git add data/vgsales_final.csv
            git rm -rf data/vgsales_updated_*.csv || echo "⚠️ No batch files to delete."
            
            if git diff --cached --quiet; then
            echo "⚠️ No changes detected, skipping commit."
            else
            git commit -m "Updated merged vgsales data"
            git push origin master
            fi
