name: Run Full Pipeline

on:
  workflow_dispatch:  # Chạy thủ công trên GitHub Actions

jobs:
  prepare:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      batch_ids: ${{ steps.set-batch.outputs.batch_ids }}  # 🔥 Xuất batch_ids để truyền sang scrape

    steps:
    
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Generate batch list
        id: set-batch
        run: |
          BATCH_IDS=$(seq 0 19 | jq -R -s 'split("\n")[:-1]' | jq -c)
          echo "Generated batch_ids: $BATCH_IDS"
          
          # 🔥 Đúng cú pháp cho GitHub Actions
          echo "batch_ids=$BATCH_IDS" >> "$GITHUB_OUTPUT"
        shell: bash

      # 🏆 Cache toàn bộ môi trường Python để dùng lại ở các job sau
      - name: Cache Python environment
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip  # Lưu cache thư viện pip
          key: python-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            python-${{ runner.os }}-

      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"


      - name: Install dependencies (if not cached)
        run: pip install -r requirements.txt
        
  crawl-list:
    needs: prepare  # 🛑 Đảm bảo chạy sau khi `prepare` hoàn thành
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Cấp quyền ghi vào repo
    strategy:
      matrix:
        batch_id: ${{ fromJson(needs.prepare.outputs.batch_ids) }}  # Chạy từng batch song song
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Sử dụng token để có quyền push

      # ✅ Dùng lại cache Python từ `prepare`
      - name: Restore Python environment
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: python-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            python-${{ runner.os }}-
            
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies (if not cached)
        run: pip install -r requirements.txt

      - name: Run Scraper for Batch ${{ matrix.batch_id }}
        run: python -u source/vgchartzfull.py ${{ matrix.batch_id }}  

      - name: Upload vgsales.csv as artifact
        uses: actions/upload-artifact@v4
        with:
          name: vgsales-data-batch-${{ matrix.batch_id }}  # Thêm batch_id vào tên artifact
          path: data/vgsales_batch_${{ matrix.batch_id }}.csv  # Đảm bảo tên file đầu ra đúng
          if-no-files-found: error  # Báo lỗi nếu file không tồn tại

  merge-batches:
    needs: crawl-list
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore Python environment
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: python-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            python-${{ runner.os }}-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies (if not cached)
        run: pip install -r requirements.txt

      - name: Download all batch files
        uses: actions/download-artifact@v4
        with:
          path: artifacts/
          merge-multiple: true  # Gộp tất cả artifacts vào thư mục data/

        
        
      - name: Move CSV files to data/
        run: |
          mkdir -p data/
          find artifacts/ -type f -name "*.csv" -exec mv {} data/ \;
          ls -l data/
        

      - name: Print folder structure
        run: |
          sudo apt-get install tree -y  # Cài đặt tree nếu chưa có (chỉ cần trên Ubuntu)
          tree data/
  
      - name: Merge batch files
        run: python -u source/merge_batches.py

      - name: Remove batch files after merging
        run: |
          find data/ -type f -name "vgsales_batch_*.csv" -exec rm {} \;
          echo "Batch files removed after merging."

      - name: Upload final merged file
        uses: actions/upload-artifact@v4
        with:
          name: vgsales-dataset
          path: data/vgsales.csv
          if-no-files-found: error

  scrape:
    needs: [prepare, merge-batches]  # 🛑 Đảm bảo chạy sau khi `prepare` hoàn thành
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Cấp quyền ghi vào repo
    timeout-minutes: 330  # ⏳ Hủy job nếu chạy quá 5 giờ 30 phút

    strategy:
      matrix:
        batch_id: ${{ fromJson(needs.prepare.outputs.batch_ids) }}
      fail-fast: false  # 🔥 Không hủy các batch khác nếu một batch bị lỗi

    steps:
      - name: Check Memory Usage
        run: free -h

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Sử dụng token để có quyền push

      # ✅ Dùng lại cache Python từ `prepare`
      - name: Restore Python environment
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: python-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            python-${{ runner.os }}-
            
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies (if not cached)
        run: pip install -r requirements.txt

      - name: Download vgsales.csv
        uses: actions/download-artifact@v4
        with:
          name: vgsales-dataset
          path: data/
  
      
      - name: Run genre.py for Batch ${{ matrix.batch_id }}
        run: python -u source/genre.py ${{ matrix.batch_id }} 3400 || echo "Script failed, check logs."
      
      
      - name: Upload CSV Progress
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: vgsales-progress-batch-${{ matrix.batch_id }}
          path: data/vgsales_updated_${{ matrix.batch_id }}.csv
          if-no-files-found: warn
          overwrite: true  # 🔥 Cho phép ghi đè nếu file đã tồn tại
      

  final-commit:
    needs: [prepare, scrape]  # Chạy sau khi tất cả batch hoàn thành
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      # ✅ Dùng lại cache Python từ `prepare`
      - name: Restore Python environment
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: python-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            python-${{ runner.os }}-
            
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies (if not cached)
        run: pip install -r requirements.txt

      - name: Download all Batch Results
        uses: actions/download-artifact@v4
        with:
          path: batch-results/

      - name: List downloaded files
        run: ls -lah batch-results/

      - name: Move all CSV files to data/
        run: |
          mkdir -p data/  # Đảm bảo thư mục `data/` tồn tại
          find batch-results/ -type f -name "vgsales_updated_*.csv" -exec mv {} data/ \;
          find batch-results/ -type f -name "vgsales.csv" -exec mv {} data/ \;
          ls -lah data/  # Kiểm tra sau khi di chuyển

        
      - name: Run merge_data.py
        run: python source/merge_data.py || echo "Merge script failed, check logs."


      - name: Commit & Push Merged Data
        run: |
            git config --global user.name "github-actions"
            git config --global user.email "actions@github.com"
            git pull --rebase origin master || echo "⚠️ Pull failed, continuing..."
            
            git add data/vgsales_final.csv
            git rm -rf data/vgsales_updated_*.csv || echo "⚠️ No batch files to delete."
            
            if git diff --cached --quiet; then
            echo "⚠️ No changes detected, skipping commit."
            else
            git commit -m "Updated merged vgsales data"
            git push origin master
            fi
